import "./css/style.css";
import "react-medium-image-zoom/dist/styles.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Theme from "./theme-provider";
import SideNavigation from "@/components/ui/side-navigation";
import Header from "@/components/ui/header";
import { PageWrapper } from "@/components/page-wrapper";
import NextTopLoader from "@/components/next-toploader";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const aspekta = localFont({
  src: [
    {
      path: "../public/fonts/Aspekta-500.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/Aspekta-650.woff2",
      weight: "650",
    },
  ],
  variable: "--font-aspekta",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="/icons/apple-touch-icon.png"
          rel="apple-touch-icon"
          sizes="180x180"
        />
        <link
          href="/icons/favicon-32x32.png"
          rel="icon"
          sizes="32x32"
          type="image/png"
        />
        <link
          href="/icons/favicon-16x16.png"
          rel="icon"
          sizes="16x16"
          type="image/png"
        />
        <link href="/icons/site.webmanifest" rel="manifest" />
        <link
          color="#353844"
          href="/icons/safari-pinned-tab.svg"
          rel="mask-icon"
        />
        <meta content="#353844" name="msapplication-TileColor" />
        <meta content="#ffffff" name="theme-color" />
      </head>
      {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body
        className={`${inter.variable} ${aspekta.variable} font-inter antialiased bg-white text-slate-800 dark:bg-slate-900 dark:text-slate-200 tracking-tight`}
      >
        <NextTopLoader />
        <Theme>
          <div className="max-w-7xl mx-auto">
            <div className="min-h-screen flex">
              <SideNavigation />

              {/* Main content */}
              <main className="grow overflow-hidden px-6">
                <div className="w-full h-full max-w-[1072px] mx-auto flex flex-col">
                  <PageWrapper>
                    <Header />
                    {children}
                  </PageWrapper>
                </div>
              </main>
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
